module.exports = [{"name":"Bread - Frozen Basket Variety","brand":"Mucus Relief Severe Cough and Congestion","type":"Standardized Grass Pollen, Grass Mix 4","cost":48,"quantity":1},
{"name":"Pastrami","brand":"Vibativ","type":"Daytime Multi-Symptom Non-Drowsy Cold and Flu","cost":67,"quantity":2},
{"name":"Corn - Mini","brand":"CC Cream Complexion Corrector Medium Broad Spectrum SPF 15","type":"CLINIQUE","cost":48,"quantity":3},
{"name":"Sorrel - Fresh","brand":"Anti-Diarrheal","type":"Ciprofloxacin","cost":31,"quantity":4},
{"name":"Mayonnaise","brand":"omeprazole/sodium bicarbonate","type":"Clarins UV Plus HP SPF 40 Day Screen High Protection","cost":96,"quantity":5},
{"name":"Cake - Mini Potato Pancake","brand":"Athlete s Foot","type":"LBEL COULEUR LUXE AMPLIFIER XP","cost":6,"quantity":6},
{"name":"Wine - Delicato Merlot","brand":"Furosemide","type":"Spongatos","cost":43,"quantity":7},
{"name":"Wine - Red, Lurton Merlot De","brand":"SAFEWAY CARE","type":"Virustat","cost":18,"quantity":8},
{"name":"Capon - Whole","brand":"Leader ibuprofen","type":"ZESTRIL","cost":12,"quantity":9},
{"name":"Bacardi Breezer - Strawberry","brand":"Albuterol Sulfate","type":"Cocyntal","cost":22,"quantity":10},
{"name":"General Purpose Trigger","brand":"Ibuprofen","type":"metformin hydrochloride","cost":31,"quantity":11},
{"name":"Mangostein","brand":"miconazole 1","type":"Dove","cost":32,"quantity":12},
{"name":"Muffin Mix - Lemon Cranberry","brand":"FACE VALUES","type":"Neutrogena Ultra Sheer Dry Touch","cost":92,"quantity":13},
{"name":"Yogurt - Cherry, 175 Gr","brand":"CAPTOPRIL","type":"Menadione","cost":24,"quantity":14},
{"name":"Soup - Clam Chowder, Dry Mix","brand":"Furosemide","type":"Quinapril","cost":6,"quantity":15},
{"name":"Snails - Large Canned","brand":"IRIS","type":"Terazosin Hydrochloride Anhydrous","cost":52,"quantity":16},
{"name":"Taro Leaves","brand":"Rifampin","type":"Lisinopril","cost":17,"quantity":17},
{"name":"Yeast Dry - Fermipan","brand":"Revlimid","type":"Fluphenazine Hydrochloride","cost":9,"quantity":18},
{"name":"Beets","brand":"Kirkland Signature Antacid","type":"Gas Relief","cost":71,"quantity":19},
{"name":"Pork - Caul Fat","brand":"Benztropine Mesylate","type":"DOCETAXEL","cost":6,"quantity":20},
{"name":"Noodles - Cellophane, Thin","brand":"Keppra","type":"Omeprazole","cost":36,"quantity":21},
{"name":"Food Colouring - Pink","brand":"MINERAL TINTED MOISTURIZER","type":"Mischievous Orange Antibacterial Foaming Hand Wash","cost":45,"quantity":22},
{"name":"Butter - Salted, Micro","brand":"Alprazolam","type":"Prednisolone","cost":56,"quantity":23},
{"name":"Cape Capensis - Fillet","brand":"Morphine Sulfate","type":"Colitis","cost":43,"quantity":24},
{"name":"Crackers - Soda / Saltins","brand":"MECLIZINE HYDROCHLORIDE","type":"Sterile Alcohol Prep Pad","cost":80,"quantity":25},
{"name":"Pastry - Mini French Pastries","brand":"Ipecacuanha Kit Refill","type":"Menstrual Pain Relief Multi-Symptom","cost":54,"quantity":26},
{"name":"Muffin Batt - Choc Chk","brand":"Strength F","type":"Koh Gen Do Maifanshi Triple Lighting Foundation","cost":48,"quantity":27},
{"name":"Tomato - Plum With Basil","brand":"Pramipexole Dihydrochloride","type":"Degree","cost":82,"quantity":28},
{"name":"Wine - Malbec Trapiche Reserve","brand":"Dr. Scholls","type":"Oxycodone and Acetaminophen","cost":16,"quantity":29},
{"name":"Aromat Spice / Seasoning","brand":"Ironman Glory","type":"Hydrocodone Bitartate and Acetaminophen","cost":40,"quantity":30},
{"name":"Beer - Sleemans Cream Ale","brand":"SUPER DEFENSE","type":"Alka-Seltzer Plus","cost":19,"quantity":31},
{"name":"Wine - White Cab Sauv.on","brand":"SmartRx Natural Pain Relief Sleeve ELBOW","type":"Cefadroxil","cost":36,"quantity":32},
{"name":"Bag - Regular Kraft 20 Lb","brand":"DIGOX","type":"Lobster","cost":79,"quantity":33},
{"name":"Sea Urchin","brand":"Greasewood","type":"Mandarin Orange Anti-Bacterial Hand Sanitizer","cost":27,"quantity":34},
{"name":"Corn Meal","brand":"Tussy Antiperspirant and Deodorant Original Fresh Spice","type":"Smart Sense ibuprofen","cost":86,"quantity":35},
{"name":"Miso Paste White","brand":"Dial Complete Antibacterial Foaming Hand Wash with Lotion","type":"Pediaderm TA","cost":77,"quantity":36},
{"name":"Sachet","brand":"Vizamyl","type":"MORELLA CERIFERA POLLEN","cost":44,"quantity":37},
{"name":"Soup - Campbells, Chix Gumbo","brand":"Carbamazepine","type":"Horse Epithelia","cost":12,"quantity":38},
{"name":"Soupfoamcont12oz 112con","brand":"DHC Salicylic Acne Toner","type":"Ropinirole Hydrochloride","cost":90,"quantity":39},
{"name":"Bread - Kimel Stick Poly","brand":"Eve Lom Radiance Lift Foundation SPF 15","type":"TRAMADOL HYDROCHLORIDE","cost":7,"quantity":40},
{"name":"Chocolate - Semi Sweet, Calets","brand":"migraine formula","type":"JUNIPERUS ASHEI POLLEN","cost":61,"quantity":41},
{"name":"Bread - French Stick","brand":"NICOTINE POLACRILEX","type":"oxycodone hydrochloride","cost":42,"quantity":42},
{"name":"Mix - Cocktail Strawberry Daiquiri","brand":"TOPCARE","type":"Strattera","cost":71,"quantity":43},
{"name":"Artichokes - Jerusalem","brand":"Kynamro","type":"Walgreens Artificial Tears Lubricant Eye Drops","cost":36,"quantity":44},
{"name":"Pear - Asian","brand":"ShopRite Childrens Ibuprofen","type":"Levofloxacin","cost":43,"quantity":45},
{"name":"Wine - White, Pelee Island","brand":"Color Me With KidsUV SPF30","type":"Wal-Fex","cost":15,"quantity":46},
{"name":"Tomatoes - Diced, Canned","brand":"KOMBIGLYZE","type":"Laser Sun Block 100 SPF50","cost":70,"quantity":47},
{"name":"Wine - Red, Lurton Merlot De","brand":"Remedy Dimethicone Moisture Barrier","type":"Euphrasia Officinalis Kit Refill","cost":41,"quantity":48},
{"name":"Lamb - Whole Head Off,nz","brand":"Indomethacin","type":"Antiseptic Mouth Rinse","cost":33,"quantity":49},
{"name":"Soupfoamcont12oz 112con","brand":"Power Relief","type":"Levofloxacin","cost":25,"quantity":50}];